# Generated by Django 2.1.2 on 2018-10-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=5)),
                ('BHK', models.IntegerField()),
                ('Price', models.FloatField(max_length=10)),
                ('Latiutude', models.FloatField(max_length=10)),
                ('Longitude', models.FloatField(max_length=10)),
                ('Category', models.IntegerField()),
                ('Area', models.IntegerField()),
                ('Balconies', models.IntegerField()),
                ('Garden', models.IntegerField()),
                ('Gym', models.IntegerField()),
                ('Outdoor_sports', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('vastu', models.IntegerField()),
            ],
        ),
    ]
