# Generated by Django 2.1.2 on 2018-10-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='properties',
            new_name='property',
        ),
    ]
