# Generated by Django 2.1.2 on 2018-10-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0002_auto_20181016_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='BHK',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Balconies',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Category',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Garden',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Gym',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Outdoor_sports',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='vastu',
            field=models.FloatField(),
        ),
    ]
