# Generated by Django 2.1.2 on 2018-10-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0003_auto_20181016_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='property',
            new_name='Product',
        ),
    ]
