# Generated by Django 2.1.2 on 2018-10-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0004_auto_20181020_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='property',
        ),
    ]
