# Generated by Django 2.1.2 on 2018-10-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0006_auto_20181021_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='BHK',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Balconies',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Garden',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Gym',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Outdoor_sports',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='vastu',
            field=models.BooleanField(),
        ),
    ]
