# Generated by Django 2.1.2 on 2018-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0007_auto_20181021_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Balconies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Garden',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Gym',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='Outdoor_sports',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='vastu',
            field=models.IntegerField(),
        ),
    ]
