db.reco_property.insertMany([
  {
    "id": 1,
    "Name": "a",
    "BHK": 1,
    "Price": 0.4,
    "Latiutude": 19.294,
    "Longitude": 72.932,
    "Category": 1,
    "Area": 500,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 2,
    "Name": "b",
    "BHK": 1,
    "Price": 0.4,
    "Latiutude": 19.243,
    "Longitude": 73.021,
    "Category": 1,
    "Area": 500,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 3,
    "Name": "c",
    "BHK": 1,
    "Price": 0.45,
    "Latiutude": 19.256,
    "Longitude": 73.052,
    "Category": 1,
    "Area": 550,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 4,
    "Name": "d",
    "BHK": 1,
    "Price": 0.45,
    "Latiutude": 19.189,
    "Longitude": 73.081,
    "Category": 1,
    "Area": 550,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 5,
    "Name": "e",
    "BHK": 1,
    "Price": 0.5,
    "Latiutude": 19.243,
    "Longitude": 72.947,
    "Category": 2,
    "Area": 550,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 6,
    "Name": "f",
    "BHK": 1,
    "Price": 0.5,
    "Latiutude": 19.184,
    "Longitude": 72.896,
    "Category": 2,
    "Area": 600,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 7,
    "Name": "g",
    "BHK": 1,
    "Price": 0.55,
    "Latiutude": 19.283,
    "Longitude": 73.029,
    "Category": 2,
    "Area": 600,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 8,
    "Name": "h",
    "BHK": 1,
    "Price": 0.55,
    "Latiutude": 19.234,
    "Longitude": 73.063,
    "Category": 2,
    "Area": 650,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 9,
    "Name": "i",
    "BHK": 1,
    "Price": 0.6,
    "Latiutude": 19.057,
    "Longitude": 73.026,
    "Category": 2,
    "Area": 650,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 10,
    "Name": "j",
    "BHK": 1,
    "Price": 0.6,
    "Latiutude": 19.138,
    "Longitude": 72.832,
    "Category": 2,
    "Area": 650,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 11,
    "Name": "k",
    "BHK": 1,
    "Price": 0.65,
    "Latiutude": 19.261,
    "Longitude": 72.982,
    "Category": 2,
    "Area": 700,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 12,
    "Name": "l",
    "BHK": 1,
    "Price": 0.65,
    "Latiutude": 19.072,
    "Longitude": 72.989,
    "Category": 2,
    "Area": 700,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 13,
    "Name": "m",
    "BHK": 1,
    "Price": 0.7,
    "Latiutude": 19.019,
    "Longitude": 72.899,
    "Category": 2,
    "Area": 700,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 14,
    "Name": "n",
    "BHK": 1,
    "Price": 0.8,
    "Latiutude": 18.987,
    "Longitude": 72.902,
    "Category": 3,
    "Area": 800,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 15,
    "Name": "o",
    "BHK": 1,
    "Price": 0.85,
    "Latiutude": 19.013,
    "Longitude": 72.985,
    "Category": 3,
    "Area": 800,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 16,
    "Name": "p",
    "BHK": 1,
    "Price": 0.85,
    "Latiutude": 19.144,
    "Longitude": 72.895,
    "Category": 3,
    "Area": 800,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 17,
    "Name": "q",
    "BHK": 1,
    "Price": 0.9,
    "Latiutude": 19.232,
    "Longitude": 72.908,
    "Category": 3,
    "Area": 850,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 18,
    "Name": "r",
    "BHK": 1,
    "Price": 0.95,
    "Latiutude": 19.021,
    "Longitude": 73.063,
    "Category": 3,
    "Area": 850,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 19,
    "Name": "s",
    "BHK": 1,
    "Price": 1,
    "Latiutude": 19.192,
    "Longitude": 73.065,
    "Category": 4,
    "Area": 900,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 20,
    "Name": "t",
    "BHK": 2,
    "Price": 1,
    "Latiutude": 19.012,
    "Longitude": 73.089,
    "Category": 1,
    "Area": 1100,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 1
  },
  {
    "id": 21,
    "Name": "u",
    "BHK": 2,
    "Price": 1.05,
    "Latiutude": 19.084,
    "Longitude": 72.945,
    "Category": 1,
    "Area": 1100,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 22,
    "Name": "v",
    "BHK": 2,
    "Price": 1.1,
    "Latiutude": 19.298,
    "Longitude": 72.908,
    "Category": 1,
    "Area": 1150,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 23,
    "Name": "w",
    "BHK": 2,
    "Price": 1.2,
    "Latiutude": 19.274,
    "Longitude": 72.962,
    "Category": 1,
    "Area": 1150,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 24,
    "Name": "x",
    "BHK": 2,
    "Price": 1.2,
    "Latiutude": 19.184,
    "Longitude": 72.835,
    "Category": 1,
    "Area": 1150,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 1
  },
  {
    "id": 25,
    "Name": "y",
    "BHK": 2,
    "Price": 1.2,
    "Latiutude": 19.143,
    "Longitude": 72.967,
    "Category": 1,
    "Area": 1200,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 1
  },
  {
    "id": 26,
    "Name": "z",
    "BHK": 2,
    "Price": 1.2,
    "Latiutude": 19.021,
    "Longitude": 72.908,
    "Category": 1,
    "Area": 1200,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 27,
    "Name": "a1",
    "BHK": 2,
    "Price": 1.2,
    "Latiutude": 19.293,
    "Longitude": 73.076,
    "Category": 1,
    "Area": 1200,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 28,
    "Name": "b1",
    "BHK": 2,
    "Price": 1.2,
    "Latiutude": 19.291,
    "Longitude": 73.067,
    "Category": 1,
    "Area": 1200,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 29,
    "Name": "c1",
    "BHK": 2,
    "Price": 1.25,
    "Latiutude": 19.153,
    "Longitude": 73.028,
    "Category": 1,
    "Area": 1100,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 30,
    "Name": "d1",
    "BHK": 2,
    "Price": 1.25,
    "Latiutude": 19.183,
    "Longitude": 72.987,
    "Category": 1,
    "Area": 1100,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 31,
    "Name": "e1",
    "BHK": 2,
    "Price": 1.25,
    "Latiutude": 19.143,
    "Longitude": 72.889,
    "Category": 1,
    "Area": 1100,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 32,
    "Name": "f1",
    "BHK": 2,
    "Price": 1.25,
    "Latiutude": 19.062,
    "Longitude": 72.902,
    "Category": 1,
    "Area": 1200,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 33,
    "Name": "g1",
    "BHK": 2,
    "Price": 1.25,
    "Latiutude": 19.091,
    "Longitude": 72.863,
    "Category": 1,
    "Area": 1200,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 1
  },
  {
    "id": 34,
    "Name": "h1",
    "BHK": 2,
    "Price": 1.3,
    "Latiutude": 19.291,
    "Longitude": 72.949,
    "Category": 2,
    "Area": 1200,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 35,
    "Name": "i1",
    "BHK": 2,
    "Price": 1.3,
    "Latiutude": 19.197,
    "Longitude": 73.026,
    "Category": 2,
    "Area": 1150,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 36,
    "Name": "j1",
    "BHK": 2,
    "Price": 1.3,
    "Latiutude": 19.285,
    "Longitude": 73.085,
    "Category": 2,
    "Area": 1250,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 37,
    "Name": "k1",
    "BHK": 2,
    "Price": 1.3,
    "Latiutude": 19.143,
    "Longitude": 73.063,
    "Category": 2,
    "Area": 1250,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 38,
    "Name": "l1",
    "BHK": 2,
    "Price": 1.3,
    "Latiutude": 19.083,
    "Longitude": 73.064,
    "Category": 2,
    "Area": 1250,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 39,
    "Name": "m1",
    "BHK": 2,
    "Price": 1.35,
    "Latiutude": 18.979,
    "Longitude": 73.089,
    "Category": 2,
    "Area": 1250,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 40,
    "Name": "n1",
    "BHK": 2,
    "Price": 1.35,
    "Latiutude": 18.972,
    "Longitude": 72.821,
    "Category": 2,
    "Area": 1250,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 41,
    "Name": "o1",
    "BHK": 2,
    "Price": 1.35,
    "Latiutude": 19.021,
    "Longitude": 72.879,
    "Category": 2,
    "Area": 1250,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 42,
    "Name": "p1",
    "BHK": 2,
    "Price": 1.35,
    "Latiutude": 19.053,
    "Longitude": 72.978,
    "Category": 2,
    "Area": 1300,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 43,
    "Name": "q1",
    "BHK": 2,
    "Price": 1.4,
    "Latiutude": 19.154,
    "Longitude": 72.963,
    "Category": 2,
    "Area": 1300,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 44,
    "Name": "r1",
    "BHK": 2,
    "Price": 1.4,
    "Latiutude": 19.143,
    "Longitude": 72.89,
    "Category": 2,
    "Area": 1300,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 45,
    "Name": "s1",
    "BHK": 2,
    "Price": 1.4,
    "Latiutude": 19.238,
    "Longitude": 72.973,
    "Category": 2,
    "Area": 1300,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 46,
    "Name": "t1",
    "BHK": 2,
    "Price": 1.4,
    "Latiutude": 19.128,
    "Longitude": 72.846,
    "Category": 2,
    "Area": 1300,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 47,
    "Name": "u1",
    "BHK": 2,
    "Price": 1.45,
    "Latiutude": 19.183,
    "Longitude": 73.046,
    "Category": 2,
    "Area": 1350,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 48,
    "Name": "v1",
    "BHK": 2,
    "Price": 1.45,
    "Latiutude": 19.264,
    "Longitude": 73.012,
    "Category": 2,
    "Area": 1350,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 49,
    "Name": "w1",
    "BHK": 2,
    "Price": 1.45,
    "Latiutude": 19.149,
    "Longitude": 73.032,
    "Category": 2,
    "Area": 1350,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 50,
    "Name": "x1",
    "BHK": 2,
    "Price": 1.45,
    "Latiutude": 19.264,
    "Longitude": 72.837,
    "Category": 2,
    "Area": 1350,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 51,
    "Name": "y1",
    "BHK": 2,
    "Price": 1.5,
    "Latiutude": 19.234,
    "Longitude": 72.978,
    "Category": 2,
    "Area": 1350,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 52,
    "Name": "z1",
    "BHK": 2,
    "Price": 1.5,
    "Latiutude": 19.042,
    "Longitude": 73.947,
    "Category": 2,
    "Area": 1400,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 53,
    "Name": "a2",
    "BHK": 2,
    "Price": 1.5,
    "Latiutude": 18.976,
    "Longitude": 72.934,
    "Category": 2,
    "Area": 1400,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 54,
    "Name": "b2",
    "BHK": 2,
    "Price": 1.5,
    "Latiutude": 18.997,
    "Longitude": 72.823,
    "Category": 2,
    "Area": 1400,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 55,
    "Name": "c2",
    "BHK": 2,
    "Price": 1.55,
    "Latiutude": 18.968,
    "Longitude": 72.947,
    "Category": 3,
    "Area": 1400,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 56,
    "Name": "d2",
    "BHK": 2,
    "Price": 1.55,
    "Latiutude": 19.045,
    "Longitude": 73.074,
    "Category": 3,
    "Area": 1400,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 0,
    "vastu": 1
  },
  {
    "id": 57,
    "Name": "e2",
    "BHK": 2,
    "Price": 1.55,
    "Latiutude": 19.028,
    "Longitude": 73.098,
    "Category": 3,
    "Area": 1300,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 58,
    "Name": "f2",
    "BHK": 2,
    "Price": 1.55,
    "Latiutude": 19.178,
    "Longitude": 72.873,
    "Category": 3,
    "Area": 1300,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 1
  },
  {
    "id": 59,
    "Name": "g2",
    "BHK": 2,
    "Price": 1.55,
    "Latiutude": 19.035,
    "Longitude": 72.845,
    "Category": 3,
    "Area": 1300,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 60,
    "Name": "h2",
    "BHK": 2,
    "Price": 1.6,
    "Latiutude": 19.136,
    "Longitude": 72.843,
    "Category": 3,
    "Area": 1350,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 0,
    "vastu": 0
  },
  {
    "id": 61,
    "Name": "i2",
    "BHK": 2,
    "Price": 1.6,
    "Latiutude": 19.048,
    "Longitude": 72.987,
    "Category": 3,
    "Area": 1350,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 62,
    "Name": "j2",
    "BHK": 2,
    "Price": 1.65,
    "Latiutude": 19.284,
    "Longitude": 72.947,
    "Category": 3,
    "Area": 1400,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 63,
    "Name": "k2",
    "BHK": 2,
    "Price": 1.65,
    "Latiutude": 19.254,
    "Longitude": 73.043,
    "Category": 3,
    "Area": 1450,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 64,
    "Name": "l2",
    "BHK": 2,
    "Price": 1.7,
    "Latiutude": 19.272,
    "Longitude": 73.032,
    "Category": 3,
    "Area": 1450,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 65,
    "Name": "m2",
    "BHK": 2,
    "Price": 1.7,
    "Latiutude": 19.154,
    "Longitude": 73.098,
    "Category": 3,
    "Area": 1450,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 66,
    "Name": "n2",
    "BHK": 2,
    "Price": 1.75,
    "Latiutude": 19.043,
    "Longitude": 72.898,
    "Category": 3,
    "Area": 1450,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 67,
    "Name": "o2",
    "BHK": 2,
    "Price": 1.75,
    "Latiutude": 19.032,
    "Longitude": 72.845,
    "Category": 3,
    "Area": 1450,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 68,
    "Name": "p2",
    "BHK": 2,
    "Price": 1.8,
    "Latiutude": 19.042,
    "Longitude": 72.892,
    "Category": 3,
    "Area": 1500,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 69,
    "Name": "q2",
    "BHK": 2,
    "Price": 1.8,
    "Latiutude": 18.968,
    "Longitude": 72.087,
    "Category": 3,
    "Area": 1500,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 70,
    "Name": "r2",
    "BHK": 2,
    "Price": 1.8,
    "Latiutude": 18.987,
    "Longitude": 72.891,
    "Category": 3,
    "Area": 1500,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 71,
    "Name": "s2",
    "BHK": 2,
    "Price": 1.8,
    "Latiutude": 19.081,
    "Longitude": 72.967,
    "Category": 3,
    "Area": 1550,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 72,
    "Name": "t2",
    "BHK": 2,
    "Price": 1.9,
    "Latiutude": 19.236,
    "Longitude": 72.973,
    "Category": 4,
    "Area": 1550,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 73,
    "Name": "u2",
    "BHK": 2,
    "Price": 1.95,
    "Latiutude": 19.128,
    "Longitude": 72.943,
    "Category": 4,
    "Area": 1500,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 74,
    "Name": "v2",
    "BHK": 2,
    "Price": 1.95,
    "Latiutude": 19.254,
    "Longitude": 73.064,
    "Category": 4,
    "Area": 1550,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 75,
    "Name": "w2",
    "BHK": 2,
    "Price": 2,
    "Latiutude": 19.239,
    "Longitude": 73.074,
    "Category": 4,
    "Area": 1600,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 76,
    "Name": "x2",
    "BHK": 2,
    "Price": 2.1,
    "Latiutude": 19.129,
    "Longitude": 73.038,
    "Category": 4,
    "Area": 1600,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 77,
    "Name": "y2",
    "BHK": 2,
    "Price": 2.1,
    "Latiutude": 19.234,
    "Longitude": 72.989,
    "Category": 4,
    "Area": 1700,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 78,
    "Name": "z2",
    "BHK": 2,
    "Price": 2.2,
    "Latiutude": 19.123,
    "Longitude": 72.844,
    "Category": 4,
    "Area": 1700,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 79,
    "Name": "a3",
    "BHK": 2,
    "Price": 2.3,
    "Latiutude": 19.243,
    "Longitude": 72.955,
    "Category": 4,
    "Area": 1750,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 80,
    "Name": "b3",
    "BHK": 2,
    "Price": 2.4,
    "Latiutude": 18.976,
    "Longitude": 72.988,
    "Category": 4,
    "Area": 1750,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 81,
    "Name": "c3",
    "BHK": 2,
    "Price": 2.5,
    "Latiutude": 18.972,
    "Longitude": 72.983,
    "Category": 4,
    "Area": 1800,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 82,
    "Name": "d3",
    "BHK": 2,
    "Price": 2.6,
    "Latiutude": 19.129,
    "Longitude": 72.938,
    "Category": 4,
    "Area": 1800,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 83,
    "Name": "e3",
    "BHK": 2,
    "Price": 2.65,
    "Latiutude": 19.028,
    "Longitude": 73.053,
    "Category": 4,
    "Area": 1800,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 84,
    "Name": "f3",
    "BHK": 3,
    "Price": 2.7,
    "Latiutude": 19.129,
    "Longitude": 73.064,
    "Category": 2,
    "Area": 1500,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 85,
    "Name": "g3",
    "BHK": 3,
    "Price": 2.8,
    "Latiutude": 19.183,
    "Longitude": 73.093,
    "Category": 2,
    "Area": 1500,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 86,
    "Name": "h3",
    "BHK": 3,
    "Price": 2.9,
    "Latiutude": 19.173,
    "Longitude": 73.043,
    "Category": 2,
    "Area": 1500,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 87,
    "Name": "i3",
    "BHK": 3,
    "Price": 3,
    "Latiutude": 19.293,
    "Longitude": 72.867,
    "Category": 2,
    "Area": 1500,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 0
  },
  {
    "id": 88,
    "Name": "j3",
    "BHK": 3,
    "Price": 3.1,
    "Latiutude": 19.028,
    "Longitude": 72.843,
    "Category": 2,
    "Area": 1500,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 89,
    "Name": "k3",
    "BHK": 3,
    "Price": 3.1,
    "Latiutude": 19.074,
    "Longitude": 72.894,
    "Category": 2,
    "Area": 1500,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 90,
    "Name": "l3",
    "BHK": 3,
    "Price": 3.2,
    "Latiutude": 18.962,
    "Longitude": 72.973,
    "Category": 2,
    "Area": 1550,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 91,
    "Name": "m3",
    "BHK": 3,
    "Price": 3.2,
    "Latiutude": 18.992,
    "Longitude": 72.943,
    "Category": 2,
    "Area": 1550,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 92,
    "Name": "n3",
    "BHK": 3,
    "Price": 3.3,
    "Latiutude": 19.021,
    "Longitude": 72.912,
    "Category": 3,
    "Area": 1600,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 93,
    "Name": "o3",
    "BHK": 3,
    "Price": 3.3,
    "Latiutude": 19.082,
    "Longitude": 72.892,
    "Category": 3,
    "Area": 1600,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 94,
    "Name": "p3",
    "BHK": 3,
    "Price": 3.35,
    "Latiutude": 19.183,
    "Longitude": 72.973,
    "Category": 3,
    "Area": 1600,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 95,
    "Name": "q3",
    "BHK": 3,
    "Price": 3.35,
    "Latiutude": 19.296,
    "Longitude": 72.897,
    "Category": 3,
    "Area": 1650,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 96,
    "Name": "r3",
    "BHK": 3,
    "Price": 3.4,
    "Latiutude": 19.123,
    "Longitude": 72.837,
    "Category": 3,
    "Area": 1650,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 97,
    "Name": "s3",
    "BHK": 3,
    "Price": 3.4,
    "Latiutude": 19.145,
    "Longitude": 73.073,
    "Category": 3,
    "Area": 1700,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 98,
    "Name": "t3",
    "BHK": 3,
    "Price": 3.5,
    "Latiutude": 19.257,
    "Longitude": 73.074,
    "Category": 3,
    "Area": 1700,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 99,
    "Name": "u3",
    "BHK": 3,
    "Price": 3.5,
    "Latiutude": 19.032,
    "Longitude": 73.094,
    "Category": 3,
    "Area": 1750,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 100,
    "Name": "v3",
    "BHK": 3,
    "Price": 3.55,
    "Latiutude": 19.294,
    "Longitude": 72.948,
    "Category": 3,
    "Area": 1750,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 101,
    "Name": "w3",
    "BHK": 3,
    "Price": 3.55,
    "Latiutude": 18.982,
    "Longitude": 72.927,
    "Category": 3,
    "Area": 1800,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 102,
    "Name": "x3",
    "BHK": 3,
    "Price": 3.6,
    "Latiutude": 18.963,
    "Longitude": 72.946,
    "Category": 3,
    "Area": 1800,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 103,
    "Name": "y3",
    "BHK": 3,
    "Price": 3.6,
    "Latiutude": 19.111,
    "Longitude": 73.028,
    "Category": 3,
    "Area": 1900,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 104,
    "Name": "z3",
    "BHK": 3,
    "Price": 3.6,
    "Latiutude": 19.121,
    "Longitude": 73.028,
    "Category": 3,
    "Area": 1900,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 105,
    "Name": "a4",
    "BHK": 3,
    "Price": 3.65,
    "Latiutude": 19.254,
    "Longitude": 73.018,
    "Category": 4,
    "Area": 1900,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 106,
    "Name": "b4",
    "BHK": 3,
    "Price": 3.65,
    "Latiutude": 19.294,
    "Longitude": 72.869,
    "Category": 4,
    "Area": 2000,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 107,
    "Name": "c4",
    "BHK": 3,
    "Price": 3.65,
    "Latiutude": 19.115,
    "Longitude": 72.943,
    "Category": 4,
    "Area": 2100,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 108,
    "Name": "d4",
    "BHK": 3,
    "Price": 3.65,
    "Latiutude": 19.293,
    "Longitude": 72.938,
    "Category": 4,
    "Area": 2100,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 109,
    "Name": "e4",
    "BHK": 3,
    "Price": 3.7,
    "Latiutude": 19.082,
    "Longitude": 72.818,
    "Category": 4,
    "Area": 2150,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 110,
    "Name": "f4",
    "BHK": 3,
    "Price": 3.7,
    "Latiutude": 18.984,
    "Longitude": 72.909,
    "Category": 4,
    "Area": 2150,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 111,
    "Name": "g4",
    "BHK": 3,
    "Price": 3.7,
    "Latiutude": 18.965,
    "Longitude": 72.901,
    "Category": 4,
    "Area": 2150,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 112,
    "Name": "h4",
    "BHK": 3,
    "Price": 3.75,
    "Latiutude": 18.991,
    "Longitude": 72.904,
    "Category": 4,
    "Area": 2200,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 113,
    "Name": "i4",
    "BHK": 3,
    "Price": 3.75,
    "Latiutude": 19.028,
    "Longitude": 72.893,
    "Category": 4,
    "Area": 2200,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 114,
    "Name": "j4",
    "BHK": 3,
    "Price": 3.75,
    "Latiutude": 19.083,
    "Longitude": 72.974,
    "Category": 4,
    "Area": 2250,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 115,
    "Name": "k4",
    "BHK": 3,
    "Price": 3.8,
    "Latiutude": 19.044,
    "Longitude": 72.893,
    "Category": 4,
    "Area": 2250,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 116,
    "Name": "l4",
    "BHK": 3,
    "Price": 3.8,
    "Latiutude": 19.099,
    "Longitude": 72.893,
    "Category": 4,
    "Area": 2300,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 117,
    "Name": "m4",
    "BHK": 3,
    "Price": 3.85,
    "Latiutude": 18.977,
    "Longitude": 72.904,
    "Category": 4,
    "Area": 2300,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 118,
    "Name": "n4",
    "BHK": 4,
    "Price": 3.2,
    "Latiutude": 18.992,
    "Longitude": 72.865,
    "Category": 2,
    "Area": 2000,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 119,
    "Name": "o4",
    "BHK": 4,
    "Price": 3.3,
    "Latiutude": 19.021,
    "Longitude": 73.068,
    "Category": 2,
    "Area": 2100,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 120,
    "Name": "p4",
    "BHK": 4,
    "Price": 3.3,
    "Latiutude": 19.128,
    "Longitude": 73.091,
    "Category": 2,
    "Area": 2100,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 121,
    "Name": "q4",
    "BHK": 4,
    "Price": 3.4,
    "Latiutude": 19.012,
    "Longitude": 73.073,
    "Category": 2,
    "Area": 2200,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 122,
    "Name": "r4",
    "BHK": 4,
    "Price": 3.5,
    "Latiutude": 19.084,
    "Longitude": 72.981,
    "Category": 2,
    "Area": 2300,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 0,
    "Outdoor_sports": 0,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 123,
    "Name": "s4",
    "BHK": 4,
    "Price": 3.6,
    "Latiutude": 19.054,
    "Longitude": 72.963,
    "Category": 3,
    "Area": 2300,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 124,
    "Name": "t4",
    "BHK": 4,
    "Price": 3.7,
    "Latiutude": 19.022,
    "Longitude": 72.893,
    "Category": 3,
    "Area": 2400,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 125,
    "Name": "u4",
    "BHK": 4,
    "Price": 3.8,
    "Latiutude": 19.284,
    "Longitude": 72.905,
    "Category": 3,
    "Area": 2450,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 126,
    "Name": "v4",
    "BHK": 4,
    "Price": 3.85,
    "Latiutude": 19.193,
    "Longitude": 73.038,
    "Category": 3,
    "Area": 2500,
    "Balconies": 0,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 127,
    "Name": "w4",
    "BHK": 4,
    "Price": 3.9,
    "Latiutude": 19.154,
    "Longitude": 73.084,
    "Category": 4,
    "Area": 2550,
    "Balconies": 0,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 128,
    "Name": "x4",
    "BHK": 4,
    "Price": 3.95,
    "Latiutude": 18.965,
    "Longitude": 72.983,
    "Category": 4,
    "Area": 2600,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 129,
    "Name": "y4",
    "BHK": 4,
    "Price": 4,
    "Latiutude": 18.982,
    "Longitude": 72.857,
    "Category": 4,
    "Area": 2650,
    "Balconies": 1,
    "Garden": 1,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  },
  {
    "id": 130,
    "Name": "z4",
    "BHK": 4,
    "Price": 4.1,
    "Latiutude": 18.972,
    "Longitude": 72.909,
    "Category": 4,
    "Area": 2700,
    "Balconies": 1,
    "Garden": 0,
    "Gym": 1,
    "Outdoor_sports": 1,
    "parking": 1,
    "vastu": 1
  }
]);